### ISSUE TITLE
JAPI plugin interface functions

### ISSUE THREAD

**Issue by KojoBailey** [Kapilarny/JAPI#8]
Rather than having function names like `JAPI_LogInfo()` or `JAPI_HookFunction()`, I believe it'd be more useful to just group those functions under the `JAPI` (or `japi`) namespace. That you way you could instead have `japi::LogInfo()` and so on instead, which feels cleaner to use.

**Comment by Kapilarny** [comment]
I disagree since the current syntax allows for C/other language bindings
